using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("Collections")]
[assembly: AssemblyDescriptionAttribute("Enhanced Collections for .NET.  Code was published at http://www.codeproject.com/" +
    "csharp/sets.asp")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("Collections")]
[assembly: AssemblyCopyrightAttribute("Declaration of code in public domain can be found in comment by Jason Smith at ht" +
    "tp://www.codeproject.com/csharp/sets.asp#xx703510xx.  Copyright © 2002-2004 by A" +
    "idant Systems, Inc., and by Jason Smith.")]
[assembly: AssemblyVersionAttribute("1.0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("3.3.0.3001")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AllowPartiallyTrustedCallersAttribute()]

[assembly: SecurityRules(SecurityRuleSet.Level1, SkipVerificationInFullTrust = true)]
