using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyTitleAttribute("NHibernate.Tool.HbmXsd")]
[assembly: AssemblyDescriptionAttribute("Tool to Generate Hbm classes for use by NHibernate")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate.Tool.HbmXsd")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("3.3.0.3001")]
[assembly: AssemblyInformationalVersionAttribute("3.3.0.3001")]
[assembly: AssemblyFileVersionAttribute("3.3.0.3001")]
[assembly: AssemblyDelaySignAttribute(false)]

